### ISSUE TITLE
Improve doc

### ISSUE THREAD

**Issue by corentinbettiol** [fvaleye/tracarbon#91]
I think the readme or the doc website is missing some explanation regarding the output of the program.

I think that `tracarbon.hardware_memory_usage` and `tracarbon.hardware_cpu_usage` are expressed in percentage?

What about `tracarbon.co2_emission`? What is the unit? Same for `tracarbon.energy_consumption`.

How to read the json file (or output to stdout)? Do we need to create a graph in order to see the consumption? Do we need to calculate a median or an average value?

**Comment by fvaleye** [comment]
Hello @corentinbettiol 👋,

Thanks for reporting this!

You are right about the missing documentation on these metrics. 
I will take time to improve the documentation to better share the definitions in the coming PR.

In the meantime, I could answer your questions.

> I think that tracarbon.hardware_memory_usage and tracarbon.hardware_cpu_usage are expressed in percentage?
You are right; these two values are expressed in %:
- `hardware_memory_usage`:  CPU used in % ([more information](https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent))
- `hardware_cpu_usage`: memory used in % ([more information](https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent))

> What about tracarbon.co2_emission? What is the unit? Same for tracarbon.energy_consumption.
- `tracarbon.co2_emission` unit is in `CO2g/kwh` emitted since the last energy measurement measured and the latest carbon emission factor of your location
- `tracarbon.energy_consumption` is the current wattage of your hardware

> How to read the json file (or output to stdout)? Do we need to create a graph in order to see the consumption? Do we need to calculate a median or an average value?

- You could read by summing all the carbon emissions based on timestamps; you could easily analyze your carbon emissions for a specific period.
- Or, you could use another exporter to export the values to a graph to analyze the consumption and the carbon emissions.

**Comment by corentinbettiol** [comment]
Sorry I missed your comment!

Thanks for the doc on the metrics :)
